### ISSUE TITLE
Conflito de versão detectado

### ISSUE THREAD

**Issue by guiniederle** [glaucia86/workshop-net-core-iniciantes#1]
Olá,

Quando instalei o pacote do Sqlite e rodei o comando "dotnet restore", está ocorrendo vários erros de conflito de versão detectado. Aí pede para que eu instale as dependências, por exemplo:

> error NU1107: Conflito de versão detectado para Microsoft.Extensions.Options. Instale/referencie Microsoft.Extensions.Options 2.2.0 diretamente no projeto workshopAspNet para resolver esse problema.

Aí preciso instalar uma por uma?

**Comment by glaucia86** [comment]
> Olá,
> 
> Quando instalei o pacote do Sqlite e rodei o comando "dotnet restore", está ocorrendo vários erros de conflito de versão detectado. Aí pede para que eu instale as dependências, por exemplo:
> 
> > error NU1107: Conflito de versão detectado para Microsoft.Extensions.Options. Instale/referencie Microsoft.Extensions.Options 2.2.0 diretamente no projeto workshopAspNet para resolver esse problema.
> 
> Aí preciso instalar uma por uma?

@guiniederle vc está com o seu projeto no GitHub? Se sim, pode me enviar o link para que eu possa dar uma olhada?

Outro detalhe: procurou usar a mesma versão do curso do SQlite?

**Comment by glaucia86** [comment]
@guiniederle 

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
  </ItemGroup>

</Project>
```

Tente usar essa versão do SQLite. Pq como ele tá mais integrado ao dotnet Core 2.x é melhor. Vou dar uma olhada no repositório oficial do SQlite para dotnet core se tá tendo problemas nessa versão que você está usando. 
Por favor, me sinalize a versão que você está usando e se alterando para a versão acima, se o problema persistirá.

Abraços,

Glaucia Lemos

**Comment by guiniederle** [comment]
Não tenho feito push no git, mas copiei o seu ItemGroup e os warnings pararam, não sei por que.

Obrigado!

**Comment by glaucia86** [comment]
@guiniederle Ahh show! Então era justamente o que eu estava pensando... problema de versão do pacote.
Qualquer outra ajuda, só sinalizar por aqui.
Vou fechar essa **issue** aqui.

Um forte abraço.
