### ISSUE TITLE
Controllers e Views

### ISSUE THREAD

**Issue by cassiolrm30** [glaucia86/workshop-net-core-iniciantes#3]
Bom dia, Glaucia,

Eu estou aprendendo .NET Core e acompanhando seu workshop, mas estou sentindo falta dos arquivos de Controller, e as views em uma pasta chamada "Pages" em vez da pasta "Views". O scaffolding do .NET Core 2.2 é assim mesmo? Ou poderíamos refazer esse projeto incluindo controllers?

Aguardo seu retorno,
Cássio

**Comment by glaucia86** [comment]
@cassiolrm30 muita coisa mudou no .NET Core.

Peço que faça uma leitura desse link aqui: https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio
