### ISSUE TITLE
Meus botões não estão ficando iguais ao do workshop

### ISSUE THREAD

**Issue by wmazoni** [glaucia86/workshop-net-core-iniciantes#4]
Eu estou usando o mesmo código glyphicon no arquivo Index.cshtml, mas nos botões não ficam os ícones como aparece no seu código. Alguém sabe o que pode estar faltando?

**Comment by glaucia86** [comment]
@wmazoni você chegou a importar direitinho o bootstrap (3.3.7)?


https://github.com/glaucia86/workshop-net-core-iniciantes/blob/master/src/FilmesCRUDRazor/Pages/Shared/_Layout.cshtml

**Comment by wmazoni** [comment]
Boa tarde, eu não tinha importado o link do bootstrap, o meu código _Layout.cshtml não tinha os links para o bootstrap. Vi que no seu código tinha os links, agora está funcionando normalmente. Obrigado

**Comment by glaucia86** [comment]
Ótimo! Fechando a issue!
