### ISSUE TITLE
Falha ao abrir o https://localhost:5001

### ISSUE THREAD

**Issue by AbnerTS** [glaucia86/workshop-net-core-iniciantes#5]
Após executar o dotnet run as dois endereços foram definidos corretamente, https://localhost:5001 e o http://localhost:5000, porém ao chama-lo pelo navegador me retorna a seguinte mensagem "Não é possível acessar esse site" - ERR_CONNECTION_RESET. 
Poderia ajudar? 
Estou utilizando o dotnet core 3.1.302 e sistema operacional windows 10 home.

Grato pela atenção.

**Comment by VConhariki** [comment]
Eu tive esse mesmo problema, resolvi digitando netsh winsock reset no terminal e reiniciando o computador.

obs: foi necessário iniciar o terminal como administrador.

espero ter ajudado.
