### ISSUE TITLE
Value cannot be null. (Parameter 'connectionString')

### ISSUE THREAD

**Issue by paulostevo** [glaucia86/workshop-net-core-iniciantes#6]
Ao executar dotnet ef Migrations add InitialCreate , gera esse erro.
Value cannot be null. (Parameter 'connectionString')

**Comment by faahiero** [comment]
Acredito que o seja ConnectionString**s** e não connectionString. Tenta pra ver se é isso.

**Comment by EdmarSantosM** [comment]
Meu  estava com mesmo problema, verifiquei o arquivo appsetting.jason e  havia digitado errado.

**Erro no meu caso  ConnectionStrin**

Após  corrigir  deu certo a criação  do Migrations
![image](https://user-images.githubusercontent.com/63933147/97924337-418efd80-1d3e-11eb-8ffe-492e1136caa4.png)
