### ISSUE TITLE
Erro  ao executar codegenerator

### ISSUE THREAD

**Issue by EdmarSantosM** [glaucia86/workshop-net-core-iniciantes#8]
Ao  executar  o comando :

**dotnet aspnet-codegenerator razorpage -m Filme -dc FilmeContext -udl -outDir Pages\Filmes --referenceScriptLibraries**

![image](https://user-images.githubusercontent.com/63933147/97929301-9aaf5f00-1d47-11eb-98f5-ddbeb403f84d.png)

Executei esste  outro comando e tentei novamente  mas o erro persiste.

![image](https://user-images.githubusercontent.com/63933147/97929399-e06c2780-1d47-11eb-94b9-3f67fa468da9.png)

**Comment by EdmarSantosM** [comment]
Após  alguma pesquisas nas  documentação e  StackOverflow   consegui  corrigir e executar o comando para  geração  do  " Scaffold".

Acredito que  o erro foi por  causa  da versão  (3.1.1).

![image](https://user-images.githubusercontent.com/63933147/97933152-b1a67f00-1d50-11eb-8332-9caaa9ec316a.png)

**Comment by glaucia86** [comment]
Isso. A versão desse treinamento é 2.x.
Fechando a issue!
