### ISSUE TITLE
Erro  ao criar  os  campos  filtro

### ISSUE THREAD

**Issue by EdmarSantosM** [glaucia86/workshop-net-core-iniciantes#9]
Ao criar o select  com  o  asp-items= Model.Generos fica apresentando  esse erro.

Tentei  alterar e renomear e também  colocar  como Models.Generos e por  desencargo  colocar todo o caminho ( FilmesCrudRazor.Models.Filme)  porém o erro persiste.

![image](https://user-images.githubusercontent.com/63933147/98758841-763e2d00-23ae-11eb-908e-aaa941b39421.png)

**Comment by EdmarSantosM** [comment]
![image](https://user-images.githubusercontent.com/63933147/98758928-a259ae00-23ae-11eb-87e8-822a8a57b826.png)

**Comment by EdmarSantosM** [comment]
![image](https://user-images.githubusercontent.com/63933147/98759114-1eec8c80-23af-11eb-87b3-0ad8b7857107.png)

**Comment by EdmarSantosM** [comment]
![image](https://user-images.githubusercontent.com/63933147/98759181-4a6f7700-23af-11eb-859e-fd5b8bee2777.png)

**Comment by glaucia86** [comment]
@EdmarSantosM conseguiu resolver a issue?

**Comment by EdmarSantosM** [comment]
Ainda não consegui, Gláucia,  tive  um problema  com  meu  note  deu "pt", estou   refazendo  para  terminar esse projeto topzera
